---
title: "Projects"
editor_options: 
  markdown: 
    wrap: 72
---

<!-- PROJECT CARD 1 -->

:::::::::: {style="max-width: 800px; margin: 0 auto;"}
::::::::: projects-container
::::: project-card
<h3>Kidney Function Post-Transplant Dashboard</h3>

<p>This interactive dashboard visualizes longitudinal estimated glomerular filtration rate (eGFR) data from a renal transplant clinical trial, allowing researchers and clinicians to explore treatment effects and patient-level trajectories over time.</p>

::: tags
<span>Longitudinal analysis</span>
<span>Interactive dashboard</span>
<span>R/Shiny</span>
:::

::: links
<a href="https://4djnll-kelly-zhu.shinyapps.io/FinalProject3/">View Project</a>
<a href="https://github.com/khz123/renal-outcomes-dashboard">GitHub</a>
:::
:::::


<!-- PROJECT CARD 2 -->

::::: project-card
<h3>Epigenetic Aging and Smoking</h3>

<p>Environmental health omics project examining smoking-related epigenetic aging across multiple epigenetic clocks using CpG-level and clock-level analyses, highlighting stronger associations in morbidity-focused clocks such as Levine’s clock. Findings suggest smoking primarily influences health-relevant biological pathways, including inflammation, vascular function, and neural regulation, rather than uniformly accelerating global epigenetic age.</p>

::: tags
<span>Regression</span>
<span>Epigenetic Aging</span>
<span>R/Bioconductor</span>
:::

::: links
<a href="https://github.com/khz123/epigenetic-age-and-smoking/blob/main/report.pdf">View Report</a>
<a href="https://github.com/khz123/epigenetic-age-and-smoking">GitHub</a>
:::
:::::


<!-- PROJECT CARD 3 -->

::::: project-card
<h3>Catastrophic Health Expenditure</h3>

<p>Explored global trends in catastrophic health expenditures since 2000 and their relationships with suicide mortality, alcohol consumption, and regional variation in health burden.</p>

::: tags
<span>Healthcare Costs</span>
<span>Data Visualization</span>
<span>Python</span>
:::

::: links
<a href="https://github.com/khz123/catastrophic-health-expenditure">GitHub</a>
:::
:::::



<!-- PROJECT CARD 4 -->

::::: project-card
<h3>Caffeine Health Analysis</h3>

<p>Reproducible analysis of caffeine, alcohol, and sleep patterns across 20
countries — containerized with Docker, managed with Make and renv.</p>

::: tags
<span>Regression</span>
<span>Docker</span>
<span>R</span>
:::

::: links
<a href="https://github.com/khz123/caffeine-health-analysis">GitHub</a>
:::
:::::
:::::::::
::::::::::
